apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-2-deployment
  labels:
    app: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: project-2-pod
  template:
    metadata:
      labels:
        app: project-2-pod
    spec:
      containers:
      - name: project-2-container
        image: mohsinbaig/project-2-image:latest
        ports:
        - containerPort: 4000
        env:
        - name: BASE_URL
          value: http://project-1-service
