apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  username: TW9oc2luIE5hd2F6IEJhaWc=
  password: QWxpIHJhemE=
stringData:
  username: admin # required field for kubernetes.io/basic-auth
  password: t0p-Secret # required field for kubernetes.io/basic-auth
